name: CI

on: pull_request

jobs:
  inspection:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Run lint
        run: yarn lint

      - name: Run lint
        run: yarn tsc
